experiment:
  seed: 42
  device: auto

dataset:
  name: cora

model:
  type: gin
  hidden_dim: 64
  num_layers: 2
  dropout: 0.5

training:
  lr: 0.001
  weight_decay: 0.0001
  epochs: 1000
  save_interval: 100
